# 0.1 Tensors

**Things that are good to know before starting**
* Matrix Algebra
* The python `numpy` library




### 0.1.1 What are tensors?

A tensor can have lots of meanings, and I hate that it does. To a mathematician, "A tensor is an object containing components which remains invariant no matter what cooridnate system you choose to describe it in because its coordinates change in a special, predictable way" [1]. To a physicist, that definition boils down to a hand-wavy intuition: "A tensor is anything that transforms like a tensor". To a computer scientist, "A tensor is a multidimensional array of numbers."

For now, we'll stick with the computer science definition. They are exactly like `numpy` arrays, just with added functionality for Deep Learning (DL).


To create a tensor of zeros:

In [2]:
# import pytorch library
import torch

# create a tensor of zeros
x = torch.zeros(20)
x

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

There are two things to note about this tensor: its shape and its contents. In this case we've set all it elements (a.k.a entries) to `0.0`. For our purposes, the above object is a *vector* or *rank 1 tensor*, since it is 1 d-imensional array or line of numbers.

A scalar can be thought of as a rank 0 tensor, and rank 2 tensors are matrices or even greyscale images! This explanation is decent for a beginners intuition for DL, but will certainly anger mathematicians.

In [21]:
# A familiar rank 2 tensor is the identity matrix
I = torch.eye(3)
print('Identity matrix in 3D space: \n', I)
noisy_tensor = torch.rand(8, 8)
print('An 8 by 8 matrix of noise: \n', noisy_tensor)

identity matrix in 3D space: 
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
an 8 by 8 matrix of noise: 
 tensor([[0.5067, 0.6223, 0.5009, 0.5862, 0.2072, 0.8908, 0.5754, 0.7992],
        [0.0761, 0.8800, 0.6511, 0.9567, 0.3908, 0.2077, 0.5643, 0.6257],
        [0.9912, 0.0504, 0.4071, 0.1169, 0.2597, 0.9438, 0.9659, 0.6621],
        [0.6483, 0.0144, 0.9687, 0.6128, 0.1858, 0.9572, 0.3776, 0.3475],
        [0.8301, 0.6787, 0.1835, 0.0495, 0.0416, 0.3640, 0.1354, 0.0657],
        [0.9910, 0.3281, 0.2735, 0.3247, 0.7514, 0.8350, 0.4247, 0.4262],
        [0.9085, 0.3873, 0.6795, 0.4940, 0.3436, 0.6066, 0.5522, 0.8308],
        [0.4434, 0.3847, 0.7489, 0.3145, 0.7269, 0.9336, 0.7203, 0.3894]])


### 0.1.2 Rank and Shape

When generating `noisy_tensor` we had to specify its shape of 8 by 8.

We use the term *shape* to describe the lengths and widths of these tensors. The shape of a tensor can be thought of as its dimensions and they tell us how many elements can be stored in the tensor, as well as the way they are arranged.

In [30]:
x = torch.zeros(20)
print('The shape of x is', x.shape, ' and its rank is ', len(x.shape))
I = torch.eye(3)
print('The shape of our identity is', I.shape, ' and its rank is ', len(I.shape))
big_tensor = torch.rand(2, 2, 3, 2)
print('The shape of this tensor: \n', big_tensor, '\n is ', big_tensor.shape, '\n while its rank is ', len(big_tensor.shape))
# notice how the shape is returned in a torch.Size object. We can index it to return specific dimensions


The shape of x is torch.Size([20])  and its rank is  1
The shape of our identity is torch.Size([3, 3])  and its rank is  2
The shape of this tensor: 
 tensor([[[[0.5314, 0.0130],
          [0.4840, 0.1022],
          [0.9237, 0.8668]],

         [[0.9909, 0.6661],
          [0.9492, 0.3323],
          [0.9356, 0.2287]]],


        [[[0.5974, 0.1048],
          [0.0860, 0.2611],
          [0.7905, 0.7163]],

         [[0.0832, 0.6680],
          [0.3632, 0.3265],
          [0.9020, 0.5058]]]]) 
 is  torch.Size([2, 2, 3, 2]) 
 while its rank is  4


You can also increase or decrease the rabnk of a tensor by adding or removing extra dimensions to them using the `unsqueeze` and `squeeze` commands respectively. Note that these DO NOT add extra data into the tensor, they just wrap existing data in an extra pair of prackets (this seemingly useless additional dimension of size 1 is called the *singleton* dimension)

In [44]:
a = torch.tensor([1.0, 2.0, 3.0])
print(f"a = {a}")
print(f"a has shape {list(a.shape)} and rank {len(a.shape)}")

a = a.unsqueeze(0) # add new dim to the 0th index
print("UNSQUEEZING")
print(f"a = {a}")
print(f"a has shape {list(a.shape)} and rank {len(a.shape)}")

a.squeeze_(0) # remove new dim to the 0th index
# adding underscore to the end of any method makes it inplace
# so I dont need to let *new a* = squeeze(*old a*)
# this saves having to write a copy to memory: useful for huge tensors!
print("SQUEEZING BACK")
print(f"a = {a}")
print(f"a has shape {list(a.shape)} and rank {len(a.shape)}")

a = tensor([1., 2., 3.])
a has shape [3] and rank 1
UNSQUEEZING
a = tensor([[1., 2., 3.]])
a has shape [1, 3] and rank 2
SQUEEZING BACK
a = tensor([1., 2., 3.])
a has shape [3] and rank 1


Singleton dimensions are automatically filled if the need arises during an operation, like addition - this breaks the rules of typical matrix algebra you learn about in school ;)

In [34]:
a = torch.rand(1, 3)
print(a)
print('+')
b = torch.rand(3, 3)
print(b)
print('=')
print (a+b)

tensor([[0.8809, 0.9910, 0.2387]])
+
tensor([[0.4236, 0.0988, 0.3767],
        [0.7340, 0.8531, 0.5838],
        [0.3873, 0.0886, 0.0947]])
=
tensor([[1.3045, 1.0898, 0.6154],
        [1.6150, 1.8441, 0.8224],
        [1.2683, 1.0797, 0.3334]])


You can repeat the contents of a tensor along a dimension using the `repeat` method

In [53]:
a = torch.tensor([1.0, 2.0, 3.0, 4.0])
print(a)
print(f"a has shape {a.shape}")

a = a.repeat(2, 3)
# The best way to read the repeat method is by looking at its arguments backwards
# here we repeat it thrice along the dim where the data is,
# then repeat that dim twice
print(a)
print(f"a now has shape {a.shape}")

tensor([1., 2., 3., 4.])
a has shape torch.Size([4])
tensor([[1., 2., 3., 4., 1., 2., 3., 4., 1., 2., 3., 4.],
        [1., 2., 3., 4., 1., 2., 3., 4., 1., 2., 3., 4.]])
a now has shape torch.Size([2, 12])


You can rearrange the contents of a tensor into a tensor of a different shape using the `view` method. The number of elements remain unchanged.

In [65]:
x = torch.randn(3, 4, 2) # 3*4*2 = 24 elements in total within this tensor
print(f"As a 24 by 1 tensor: \n {x.view(24)}")
print(f"As a 8 by 3 tensor: \n {x.view(8,3)}")

As a 24 by 1 tensor: 
 tensor([ 1.1540, -1.2635, -0.7792,  1.0439,  0.3957, -0.3714, -0.6501, -0.4618,
        -1.1161, -1.8036, -3.5115,  0.0693,  0.7241,  0.3824, -0.2927,  0.3986,
        -1.4391,  0.9888, -0.2673, -0.1706, -0.1322,  0.1269, -0.0269, -0.3146])
As a 8 by 3 tensor: 
 tensor([[ 1.1540, -1.2635, -0.7792],
        [ 1.0439,  0.3957, -0.3714],
        [-0.6501, -0.4618, -1.1161],
        [-1.8036, -3.5115,  0.0693],
        [ 0.7241,  0.3824, -0.2927],
        [ 0.3986, -1.4391,  0.9888],
        [-0.2673, -0.1706, -0.1322],
        [ 0.1269, -0.0269, -0.3146]])


If you are reshaping the tensor like this, you can make sure the representation of the tensor in memory respects this new shape using the `contiguous` method. This  makes a copy of the tensor where the order of its elements in memory is the same as if it had been created from scratch.

In [66]:
x = torch.randn(3, 4, 2)
x.view(3, 8).contiguous

<function Tensor.contiguous>

### 0.1.3 Indexing
Indexing lets you access subsets of the data stored in tensors, and tensors can be indexed just like numpy arrays.

In [60]:
# remember, we index elemnts along each dim starting from 0
x = torch.rand(10, 4, 3)

# first of the 10 elements in the first dimension
print(x[0].shape)

# colon operator allows you to select everything up to
print(x[:5].shape)

# colon also lets you select all data along a given dimension
# this returns all data along the first dim, and then just the 4th element
# thats along the 2nd dim
print(x[:, 3].shape)

torch.Size([4, 3])
torch.Size([5, 4, 3])
torch.Size([10, 3])


### 0.1.4 Arithmetic
Tensors support the standard broadcasting operations from `numpy`

In [11]:
# Operations are broadcast across all elements
x = torch.zeros(20)
x = x+10
print('by broadcasting, x + 10 =', x)

by broadcasting, x + 10 = tensor([10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
        10., 10., 10., 10., 10., 10.])


In [12]:
# This does not depend on the rank or shape of the tensor
print('3 times idenity matrix = \n', 3*I)

3 times idenity matrix = 
 tensor([[3., 0., 0.],
        [0., 3., 0.],
        [0., 0., 3.]])


### 0.1.5 Data Management
By default, tensor elements are stored as floating point and used in the CPU.

In [69]:
x = torch.rand(3,3)
print(x.dtype)

# to cast them as 64 bit int
print(x.long().dtype)

torch.float32
torch.int64


In [77]:
# To send the data to the GPU instead
x = torch.rand(3,3)

# check current device tensor gets sent to
print(x.device)
if torch.cuda.is_available():
    x = x.cuda()
    print(x.device)
else:
    print('CUDA is not available on this device')

cpu
CUDA is not available on this device


If CUDA was avaialble, all subsequent operations on the tensor would run on the GPU and be really quick. `x.cpu()` would bring it back to the cpu.

# 0.2 Datasets

Data is the bread and butter of all kinds of machine learning. PyTorch comes with several python libraries for different kinds of datasets: `torchvision` for image data, `torchaudio` for audio datasets and `torchtext` for, you guessed it, text based data. We'll explore the basics of `torchvision` here because it follows on quite nicely from tensors we've just covered.



# References
[1] EigenChris, [Tensors for Beginners 0: Tensor Definition](https://youtu.be/TvxmkZmBa-k)